# Generated by Django 2.2.16 on 2022-08-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0004_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='recipes', to='foodgram.Tag', verbose_name='Список id тегов'),
        ),
    ]
