# Generated by Django 2.2.16 on 2022-08-19 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0008_auto_20220819_2120'),
    ]

    atomic = False

    operations = [
        migrations.RenameModel(
            old_name='Ingridient',
            new_name='Ingredient',
        ),
    ]
